version: '3.9'

services:
  server:
    build: ./
    env_file:
      - .env
    container_name: chat_server
    ports:
      - 9000:9000
    depends_on:
     - postgres
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: chat_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
